### ISSUE TITLE
Tags aren't processed inside of function tags

### ISSUE THREAD

**Issue by tomaka** [nickel-org/rust-mustache#10]
If you take a template like this: `{{#my_fn}} {{foo}} {{/my_fn}}`

And build it with:

```rust
MapBuilder::new()
    .insert_str("foo", "hello")
    .insert_fn("my_fn", move |input| {
        println!("{:?}", input);
        format!("")
    });
```

The value of `input` is ` {{foo}} ` instead of ` hello ` as expected.

I don't really know what the specs say, but with the Javascript implementation the inside of function tags being processed as well.

**Comment by tomaka** [comment]
Ah, in fact they are processed *after* the function has returned.

For example:

```rust
extern crate mustache;

fn main() {
    let template = mustache::compile_str("{{#my_fn}} {{foo}} {{/my_fn}}");

    let map = mustache::MapBuilder::new()
        .insert_str("foo", "hello")
        .insert_fn("my_fn", move |input| {
            println!("{:?}", input);
            input
        }).build();

    let mut output = Vec::new();
    template.render_data(&mut output, &map);

    println!("{:?}", output);
}
```

Prints ` {{foo}} ` (the value of input), and `[32, 104, 101, 108, 108, 111, 32]` which is `hello`.

It's still an issue, as in Javascript the value of `input` is directly `hello`.

**Comment by Ryman** [comment]
According to the spec this behavior is expected:
````yaml
  - name: Section
    desc: Lambdas used for sections should receive the raw section string.
    data:
      x: 'Error!'
      lambda: !code
        ruby:    'proc { |text| text == "{{x}}" ? "yes" : "no" }'
        perl:    'sub { $_[0] eq "{{x}}" ? "yes" : "no" }'
        js:      'function(txt) { return (txt == "{{x}}" ? "yes" : "no") }'
        php:     'return ($text == "{{x}}") ? "yes" : "no";'
        python:  'lambda text: text == "{{x}}" and "yes" or "no"'
        clojure: '(fn [text] (if (= text "{{x}}") "yes" "no"))'
    template: "<{{#lambda}}{{x}}{{/lambda}}>"
    expected: "<yes>"
````
