### ISSUE TITLE
bug: render_utag: unexpected value VecVal([])

### ISSUE THREAD

**Issue by MaulingMonkey** [nickel-org/rust-mustache#72]
I've created a minimal repro case to reproduce this panic, which requests I file an issue:
```
thread 'main' panicked at 'bug: render_utag: unexpected value VecVal([]). Please report this issue on GitHub if you find an input that triggers this case.', C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\mustache-0.9.0\src\template.rs:224:25
```

## Cargo.toml
```toml
[package]
name    = "mustache-bug-repo"
version = "0.1.0"
edition = "2018"

[dependencies]
mustache = "=0.9.0"
```

## src/main.rs
```rust
fn main() {
    let template = mustache::compile_str("{{authors}}").unwrap();
    let data = mustache::MapBuilder::new()
        .insert_vec("authors", |v| v)
        .build();
    let r = template.render_data_to_string(&data).unwrap();
}
```
